name: Jekyll site CI

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Choose the Ruby version that matches your local environment
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Check out the resulting site
        run: ls _site
