name: Jekyll site CI

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install dependencies
        run: |
          gem install bundler -v 2.5.7
          bundle install

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      - name: Check out the resulting site
        run: |
          ls _site
